initialization .env et db.js
ComicScrip/lyon-react-mars22-p2g5-api pull request #1
Opened 2022-04-26 15:02 UTC by Claiirou

2022-04-28 14:48 UTC, ComicScrip requested changes, later dismissed

2022-04-28 14:48 UTC, ComicScrip commented on src/app.js
> +    res.send(jokes);
on pourrait ne renvoyer qu'une blague => `jokes[0]`

2022-04-28 14:48 UTC, ComicScrip commented on src/app.js
> +    const [[jokes]] = await db
jokes => joke

2022-04-29 08:30 UTC, timonicolaux approved these changes

2022-04-29 08:47 UTC, NycoChavanoud approved these changes

2022-04-29 08:49 UTC, timonicolaux approved these changes

2022-04-29 09:05 UTC, merged